# Generated by Django 5.2.6 on 2025-10-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("route_id", models.AutoField(primary_key=True, serialize=False)),
                ("route_name", models.CharField(max_length=100, unique=True)),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("distance", models.FloatField(help_text="Distance in kilometers")),
                (
                    "estimated_duration",
                    models.DurationField(help_text="Estimated travel time"),
                ),
                (
                    "fare_per_km",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
                ),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("intercity", "Intercity"),
                            ("interstate", "Interstate"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "routes",
                "ordering": ["route_name"],
            },
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                (
                    "frequency_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Frequency in minutes"
                    ),
                ),
                ("is_operational", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_routes",
                        to="users.bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_buses",
                        to="route.route",
                    ),
                ),
            ],
            options={
                "db_table": "bus_routes",
                "unique_together": {("bus", "route", "departure_time")},
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_name", models.CharField(max_length=100)),
                ("stop_sequence", models.PositiveIntegerField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "distance_from_source",
                    models.FloatField(
                        default=0.0, help_text="Distance from source in km"
                    ),
                ),
                ("estimated_arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "fare_from_source",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_major_stop", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="route.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_stops",
                "ordering": ["route", "stop_sequence"],
                "unique_together": {("route", "stop_sequence")},
            },
        ),
        migrations.CreateModel(
            name="LiveRouteTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_latitude", models.FloatField()),
                ("current_longitude", models.FloatField()),
                (
                    "current_speed",
                    models.FloatField(default=0.0, help_text="Speed in km/h"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("to_destination", "To Destination"),
                            ("to_source", "To Source"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_arrival_next_stop",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bus_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_tracking",
                        to="route.busroute",
                    ),
                ),
                (
                    "current_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="route.routestop",
                    ),
                ),
            ],
            options={
                "db_table": "live_route_tracking",
                "ordering": ["-last_updated"],
            },
        ),
    ]
